

NEGRO = (0, 0, 0)
GRIS = (41, 41, 41)
BLANCO = (255, 255, 255)
BLANCO_OSCURO = (200, 200, 200)
VERDE = (0, 255, 0)
MARRON = (182, 143, 64)
WIGHT = 1280
HEIGHT = 720
ANCHO_BARRA = 500
ALTO_BARRA = 50

TITULO_JUEGO = "EMPTY SOLDIER"
FUENTE_BARRA = 30

RETROCEDER = "ATRAS"
TIPO_LETRA = "assets/Alice_in_Wonderland_3.ttf"


# estas no son constantes, con variables 
#----------------------------------------
NOMBRE_PARTIDA = "PARTIDA NUEVA"
NOMBRE_PERSONAJE = "NOMBRE PERSONAJE"
#---------------------------------------

ELEGIR_PARTIDA = "ELEGIR PARTIDA"

CONTROLES = "CONTROLES"

GRAFICOS = "GRAFICOS"

AUDIO = "AUDIO" 

OPCIONES = "OPCIONES"

CREDITOS = "CREDITOS"

INICIAR_PARTIDA = "INICIAR PARTIDA"

SALIR_DEL_JUEGO = "SALIR DEL JUEGO"


LISTA = ["CREDITOS DEL JUEGO:", "YORDI GUARDA", "MARCELO COMPAI","MATIAS CARREÑO", "BENJAMIN CONTRERAS", "BRAYAN OYARZO"]

FONDO = "assets/Fondo.png"